; ====================================================================
; NAP TELECOM - ARI CONFIGURATION (Asterisk REST Interface)
; ====================================================================

[general]
enabled = yes
pretty = yes
allowed_origins = 127.0.0.1:3000,localhost:3000

[nap_admin]
type = user
read_only = no
password_format = plain
#include "/etc/asterisk/ari_secret.conf"
