; ====================================================================
; NAP TELECOM - ASTERISK 20+ NATIVE CONFIGURATION
; Motor de Telefonia & Voz para Call Center de Provedores com IA
; ====================================================================

[general]
enabled = yes
bindaddr = 0.0.0.0
bindport = 8088
tlsenable = yes
tlsbindaddr = 0.0.0.0:8089
; tlscertfile = /etc/asterisk/keys/asterisk.crt
; tlsprivatekey = /etc/asterisk/keys/asterisk.key
session_limit = 100
session_inactivity = 30000
session_keep_alive = 30000
