; ====================================================================
; NAP TELECOM - AMI CONFIGURATION (Asterisk Manager Interface)
; ====================================================================

[general]
enabled = yes
port = 5038
bindaddr = 127.0.0.1
displayconnects = no

[nap_admin]
read = system,call,log,verbose,command,agent,user,config,dtmf,reporting,cdr,dialplan
write = system,call,log,verbose,command,agent,user,config,dtmf,reporting,cdr,dialplan
#include "/etc/asterisk/manager_secret.conf"
