; ====================================================================
; NAP TELECOM - PJSIP CONFIGURATION
; ====================================================================

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[transport-wss]
type=transport
protocol=wss
bind=0.0.0.0:8089

; ====================================================================
; AOR & AUTH TEMPLATES PARA WEBPHONE (WEBRTC)
; ====================================================================
[webrtc-aor](!)
type=aor
max_contacts=2
remove_existing=yes

[webrtc-auth](!)
type=auth
auth_type=userpass

[webrtc-endpoint](!)
type=endpoint
transport=transport-wss
context=from-internal
disallow=all
allow=opus,ulaw,alaw
aors=webrtc-aor
auth=webrtc-auth
webrtc=yes
dtls_auto_generate_cert=yes
dtls_verify=fingerprint
dtls_setup=actpass
ice_support=yes
media_encryption=dtls
use_avpf=yes
media_use_received_transport=yes
rtcp_mux=yes

; Exemplo Ramal Operador
[2001](webrtc-endpoint)
aors=2001
auth=2001
callerid="Operador NAP" <2001>

[2001](webrtc-aor)
[2001](webrtc-auth)
password=sip_pass_2001_webrtc
