; ====================================================================
; NAP TELECOM - RTP CONFIGURATION (RTP.CONF)
; ====================================================================

[general]
rtpstart=10000
rtpend=20000
strictrtp=yes
probation=8
icesupport=yes
