/**
 * NAP (Núcleo de Atendimento ao Provedor) - Sistema de Autenticação e RBAC
 * Arquitetura Centralizada de Controle de Acesso por Papéis e Permissões Granulares
 */

export type UserRole = 
  | 'ADMIN'
  | 'GESTOR'
  | 'NOC'
  | 'SUPORTE'
  | 'FINANCEIRO'
  | 'CAMPO'
  | 'ATENDIMENTO'
  | 'AUDITOR';

export type Permission =
  // OLT (GPON / EPON)
  | 'OLT_READ'
  | 'OLT_CREATE'
  | 'OLT_UPDATE'
  | 'OLT_DELETE'
  | 'OLT_DISCOVERY'
  // ONU / CPE
  | 'ONU_READ'
  | 'ONU_PROVISION'
  | 'ONU_REBOOT'
  | 'ONU_ENABLE'
  | 'ONU_DISABLE'
  | 'ONU_DELETE'
  | 'ONU_BATCH'
  // Customer 360 / CRM
  | 'CUSTOMER_READ'
  | 'CUSTOMER_CREATE'
  | 'CUSTOMER_UPDATE'
  | 'CUSTOMER_DELETE'
  | 'CUSTOMER_UNBLOCK'
  // Financeiro / Cobrança / Faturas
  | 'INVOICE_READ'
  | 'INVOICE_CREATE'
  | 'INVOICE_CANCEL'
  | 'PAYMENT_READ'
  | 'PAYMENT_RECONCILE'
  | 'PAYMENT_PROCESS'
  // Telefonia / Asterisk 20+
  | 'ASTERISK_READ'
  | 'ASTERISK_CONTROL'
  // GenieACS TR-069
  | 'GENIEACS_READ'
  | 'GENIEACS_WRITE'
  | 'GENIEACS_RESET'
  // Zabbix NOC
  | 'ZABBIX_READ'
  | 'ZABBIX_ACK'
  // IPAM & NSoT
  | 'IPAM_READ'
  | 'IPAM_WRITE'
  // Help Desk / Chamados
  | 'HELPDESK_READ'
  | 'HELPDESK_WRITE'
  | 'HELPDESK_CLOSE'
  // Field Service
  | 'FIELD_READ'
  | 'FIELD_WRITE'
  // Auditoria
  | 'AUDIT_READ'
  | 'AUDIT_EXPORT'
  // Configurações Globais / Setup
  | 'SYSTEM_CONFIG'
  | 'SYSTEM_SETUP';

export interface AuthenticatedUser {
  id: string;
  email: string;
  nome: string;
  role: UserRole;
  permissions: Permission[];
  ip?: string;
  issuedAt?: number;
}

// Matriz RBAC oficial do NAP (Single-Tenant Provedor)
export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  ADMIN: [
    'OLT_READ', 'OLT_CREATE', 'OLT_UPDATE', 'OLT_DELETE', 'OLT_DISCOVERY',
    'ONU_READ', 'ONU_PROVISION', 'ONU_REBOOT', 'ONU_ENABLE', 'ONU_DISABLE', 'ONU_DELETE', 'ONU_BATCH',
    'CUSTOMER_READ', 'CUSTOMER_CREATE', 'CUSTOMER_UPDATE', 'CUSTOMER_DELETE', 'CUSTOMER_UNBLOCK',
    'INVOICE_READ', 'INVOICE_CREATE', 'INVOICE_CANCEL',
    'PAYMENT_READ', 'PAYMENT_RECONCILE', 'PAYMENT_PROCESS',
    'ASTERISK_READ', 'ASTERISK_CONTROL',
    'GENIEACS_READ', 'GENIEACS_WRITE', 'GENIEACS_RESET',
    'ZABBIX_READ', 'ZABBIX_ACK',
    'IPAM_READ', 'IPAM_WRITE',
    'HELPDESK_READ', 'HELPDESK_WRITE', 'HELPDESK_CLOSE',
    'FIELD_READ', 'FIELD_WRITE',
    'AUDIT_READ', 'AUDIT_EXPORT',
    'SYSTEM_CONFIG', 'SYSTEM_SETUP'
  ],
  GESTOR: [
    'OLT_READ', 'ONU_READ',
    'CUSTOMER_READ', 'CUSTOMER_CREATE', 'CUSTOMER_UPDATE', 'CUSTOMER_UNBLOCK',
    'INVOICE_READ', 'INVOICE_CREATE', 'INVOICE_CANCEL',
    'PAYMENT_READ', 'PAYMENT_RECONCILE',
    'ASTERISK_READ', 'GENIEACS_READ', 'ZABBIX_READ', 'IPAM_READ',
    'HELPDESK_READ', 'HELPDESK_WRITE', 'HELPDESK_CLOSE',
    'FIELD_READ', 'FIELD_WRITE',
    'AUDIT_READ', 'SYSTEM_CONFIG'
  ],
  NOC: [
    'OLT_READ', 'OLT_CREATE', 'OLT_UPDATE', 'OLT_DISCOVERY',
    'ONU_READ', 'ONU_PROVISION', 'ONU_REBOOT', 'ONU_ENABLE', 'ONU_DISABLE', 'ONU_BATCH',
    'CUSTOMER_READ', 'ASTERISK_READ',
    'GENIEACS_READ', 'GENIEACS_WRITE', 'GENIEACS_RESET',
    'ZABBIX_READ', 'ZABBIX_ACK',
    'IPAM_READ', 'IPAM_WRITE',
    'HELPDESK_READ', 'HELPDESK_WRITE',
    'FIELD_READ',
    'AUDIT_READ'
  ],
  SUPORTE: [
    'OLT_READ', 'ONU_READ', 'ONU_REBOOT',
    'CUSTOMER_READ', 'CUSTOMER_UPDATE', 'CUSTOMER_UNBLOCK',
    'INVOICE_READ',
    'ASTERISK_READ', 'ASTERISK_CONTROL',
    'GENIEACS_READ', 'GENIEACS_WRITE',
    'ZABBIX_READ',
    'IPAM_READ',
    'HELPDESK_READ', 'HELPDESK_WRITE', 'HELPDESK_CLOSE',
    'FIELD_READ'
  ],
  FINANCEIRO: [
    'CUSTOMER_READ', 'CUSTOMER_UPDATE', 'CUSTOMER_UNBLOCK',
    'INVOICE_READ', 'INVOICE_CREATE', 'INVOICE_CANCEL',
    'PAYMENT_READ', 'PAYMENT_RECONCILE', 'PAYMENT_PROCESS',
    'HELPDESK_READ', 'HELPDESK_WRITE',
    'AUDIT_READ'
  ],
  CAMPO: [
    'OLT_READ', 'ONU_READ', 'ONU_PROVISION', 'ONU_REBOOT',
    'CUSTOMER_READ',
    'GENIEACS_READ',
    'FIELD_READ', 'FIELD_WRITE',
    'HELPDESK_READ'
  ],
  ATENDIMENTO: [
    'CUSTOMER_READ', 'CUSTOMER_UPDATE', 'CUSTOMER_UNBLOCK',
    'INVOICE_READ',
    'ASTERISK_READ', 'ASTERISK_CONTROL',
    'HELPDESK_READ', 'HELPDESK_WRITE'
  ],
  AUDITOR: [
    'CUSTOMER_READ', 'INVOICE_READ', 'PAYMENT_READ',
    'OLT_READ', 'ONU_READ', 'ASTERISK_READ', 'GENIEACS_READ',
    'ZABBIX_READ', 'IPAM_READ', 'HELPDESK_READ', 'FIELD_READ',
    'AUDIT_READ', 'AUDIT_EXPORT'
  ]
};
